# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/federico/Shared/Projects/17-fem1d-17-fem1d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/federico/Shared/Projects/17-fem1d-17-fem1d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/federico/Shared/Projects/17-fem1d-17-fem1d/CMakeFiles /media/federico/Shared/Projects/17-fem1d-17-fem1d//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/federico/Shared/Projects/17-fem1d-17-fem1d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 17_fem1d_17_fem1d

# Build rule for target.
17_fem1d_17_fem1d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 17_fem1d_17_fem1d
.PHONY : 17_fem1d_17_fem1d

# fast build rule for target.
17_fem1d_17_fem1d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/build
.PHONY : 17_fem1d_17_fem1d/fast

#=============================================================================
# Target rules for targets named Google_Tests_run

# Build rule for target.
Google_Tests_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Google_Tests_run
.PHONY : Google_Tests_run

# fast build rule for target.
Google_Tests_run/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/CMakeFiles/Google_Tests_run.dir/build.make Google_tests/CMakeFiles/Google_Tests_run.dir/build
.PHONY : Google_Tests_run/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/fem1d.o: src/fem1d.cpp.o
.PHONY : src/fem1d.o

# target to build an object file
src/fem1d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/fem1d.cpp.o
.PHONY : src/fem1d.cpp.o

src/fem1d.i: src/fem1d.cpp.i
.PHONY : src/fem1d.i

# target to preprocess a source file
src/fem1d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/fem1d.cpp.i
.PHONY : src/fem1d.cpp.i

src/fem1d.s: src/fem1d.cpp.s
.PHONY : src/fem1d.s

# target to generate assembly for a file
src/fem1d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/fem1d.cpp.s
.PHONY : src/fem1d.cpp.s

src/function.o: src/function.cpp.o
.PHONY : src/function.o

# target to build an object file
src/function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/function.cpp.o
.PHONY : src/function.cpp.o

src/function.i: src/function.cpp.i
.PHONY : src/function.i

# target to preprocess a source file
src/function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/function.cpp.i
.PHONY : src/function.cpp.i

src/function.s: src/function.cpp.s
.PHONY : src/function.s

# target to generate assembly for a file
src/function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/function.cpp.s
.PHONY : src/function.cpp.s

src/grid1D.o: src/grid1D.cpp.o
.PHONY : src/grid1D.o

# target to build an object file
src/grid1D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/grid1D.cpp.o
.PHONY : src/grid1D.cpp.o

src/grid1D.i: src/grid1D.cpp.i
.PHONY : src/grid1D.i

# target to preprocess a source file
src/grid1D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/grid1D.cpp.i
.PHONY : src/grid1D.cpp.i

src/grid1D.s: src/grid1D.cpp.s
.PHONY : src/grid1D.s

# target to generate assembly for a file
src/grid1D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/grid1D.cpp.s
.PHONY : src/grid1D.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/phi_function.o: src/phi_function.cpp.o
.PHONY : src/phi_function.o

# target to build an object file
src/phi_function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/phi_function.cpp.o
.PHONY : src/phi_function.cpp.o

src/phi_function.i: src/phi_function.cpp.i
.PHONY : src/phi_function.i

# target to preprocess a source file
src/phi_function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/phi_function.cpp.i
.PHONY : src/phi_function.cpp.i

src/phi_function.s: src/phi_function.cpp.s
.PHONY : src/phi_function.s

# target to generate assembly for a file
src/phi_function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/phi_function.cpp.s
.PHONY : src/phi_function.cpp.s

src/quadrature.o: src/quadrature.cpp.o
.PHONY : src/quadrature.o

# target to build an object file
src/quadrature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/quadrature.cpp.o
.PHONY : src/quadrature.cpp.o

src/quadrature.i: src/quadrature.cpp.i
.PHONY : src/quadrature.i

# target to preprocess a source file
src/quadrature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/quadrature.cpp.i
.PHONY : src/quadrature.cpp.i

src/quadrature.s: src/quadrature.cpp.s
.PHONY : src/quadrature.s

# target to generate assembly for a file
src/quadrature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/quadrature.cpp.s
.PHONY : src/quadrature.cpp.s

src/thomas.o: src/thomas.cpp.o
.PHONY : src/thomas.o

# target to build an object file
src/thomas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/thomas.cpp.o
.PHONY : src/thomas.cpp.o

src/thomas.i: src/thomas.cpp.i
.PHONY : src/thomas.i

# target to preprocess a source file
src/thomas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/thomas.cpp.i
.PHONY : src/thomas.cpp.i

src/thomas.s: src/thomas.cpp.s
.PHONY : src/thomas.s

# target to generate assembly for a file
src/thomas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/17_fem1d_17_fem1d.dir/build.make CMakeFiles/17_fem1d_17_fem1d.dir/src/thomas.cpp.s
.PHONY : src/thomas.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... 17_fem1d_17_fem1d"
	@echo "... Google_Tests_run"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/fem1d.o"
	@echo "... src/fem1d.i"
	@echo "... src/fem1d.s"
	@echo "... src/function.o"
	@echo "... src/function.i"
	@echo "... src/function.s"
	@echo "... src/grid1D.o"
	@echo "... src/grid1D.i"
	@echo "... src/grid1D.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/phi_function.o"
	@echo "... src/phi_function.i"
	@echo "... src/phi_function.s"
	@echo "... src/quadrature.o"
	@echo "... src/quadrature.i"
	@echo "... src/quadrature.s"
	@echo "... src/thomas.o"
	@echo "... src/thomas.i"
	@echo "... src/thomas.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

