# Advanced mathematical functions showcase
[problem]
dimension = 2
mesh_file = "mesh/square.msh"
output_file = "output/advanced_math"
grid_size = 100

[equation]
diffusion_coefficient = 1.0
transport_coefficient = 0.0
reaction_coefficient = 0.0

# Complex forcing function using multiple mathematical operations
forcing_function = "sin(2*pi*x)*cos(3*pi*y) + exp(-5*((x-0.5)^2 + (y-0.5)^2)) + 0.1*x^3*y^2"

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"

# Boundary conditions with advanced expressions
[[boundary_condition]]
type = "dirichlet"
tag = 1
function = "x > 0.5 ? sin(pi*x) : cos(pi*x)"  # Conditional function

[[boundary_condition]]
type = "neumann"
tag = 2
function = "sqrt(x^2 + y^2) * log(1 + abs(x - y))"  # Radial function

[[boundary_condition]]
type = "dirichlet"
tag = 3
function = "max(0, 1 - 10*((x-0.2)^2 + (y-0.8)^2))"  # Localized bump

[[boundary_condition]]
type = "neumann"
tag = 4
function = "sinh(x) + cosh(y) + tanh(x*y)"  # Hyperbolic functions
