# Simple example using only constants (backward compatible)
[problem]
dimension = 1
mesh_file = "mesh/default.msh"
output_file = "output/simple_constants"
grid_size = 100

[equation]
# Old style - just use coefficient values as function expressions
diffusion_coefficient = 1.0    # Will be read as diffusion_function = "1.0"
transport_coefficient = 0.0    # Will be read as transport_function = "0.0"
reaction_coefficient = 0.0     # Will be read as reaction_function = "0.0"
forcing_function = "sin(pi*x)"

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"

[[boundary_condition]]
type = "dirichlet"
tag = 0
function = "0.0"

[[boundary_condition]]
type = "dirichlet"
tag = 1
function = "1.0"
