# Unified approach - everything is a function expression
[problem]
dimension = 2
mesh_file = "mesh/square.msh"
output_file = "output/unified_solution"
grid_size = 100

[equation]
# Method 1: Use constant values (backward compatible)
diffusion_coefficient = 1.0
transport_coefficient = 0.5
reaction_coefficient = 0.1

# Method 2: Use function expressions (these take priority if present)
diffusion_function = "1.0 + 0.5*sin(pi*x)*cos(pi*y)"
transport_function = "x^2 + y^2"
reaction_function = "exp(-10*((x-0.5)^2 + (y-0.5)^2))"

forcing_function = "sin(2*pi*x)*cos(2*pi*y)"

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"

[[boundary_condition]]
type = "dirichlet"
tag = 1
function = "0.0"

[[boundary_condition]]
type = "neumann"
tag = 2
function = "sin(pi*x) + cos(pi*y)"
