[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-5_gmsh22.msh"
output_file = "output/debug_test"

[quadrature]
type = "order2"

[equation]
# Funzioni costanti semplici per debug
diffusion_function = "1"
transport_function_x = "0"
transport_function_y = "0"
reaction_function = "0"  
forcing_function = "1"

# Minimal boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "0"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "0"

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "0"

[[boundary_conditions]]
type = "dirichlet"
tag = 4
function = "0"

[solver]
tolerance = 1e-6
max_iterations = 50
method = "direct"
