# Time-dependent 2D diffusion-reaction problem
# u_t - div(D*grad(u)) + r*u = f(x,y,t)
# Mixed boundary conditions: Dirichlet and time-dependent Neumann

[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.012500_gmsh22.msh"
output_file = "output/diffusion_2d_td"
time_dependent = true

[quadrature]
type = "order2"

[equation]
diffusion_coefficient = 1.0
transport_coefficient = 0.0
reaction_coefficient = 0.5
forcing_function = "0"  # static fallback

[time_dependent]
final_time = 1.0
time_step = 0.005
theta = 0.5  # Crank-Nicolson
initial_condition = "exp(-((x-0.5)^2 + (y-0.5)^2)/0.1)"  # Gaussian initial
forcing_function_td = "sin(2*pi*x*y) * exp(-t)"

# Mixed boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "0.0"
time_function = "sin(t) * x * y"  # time-dependent Dirichlet

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "0.0"  # static Dirichlet

[[boundary_conditions]]
type = "neumann"
tag = 2
function = "0.0"
time_function = "cos(t) * (x + y)"  # time-dependent Neumann

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "0.0"  # static Dirichlet

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"
