[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-5_gmsh22.msh"
output_file = "output/heat_conduction"

[quadrature]
type = "order2"

[equation]
# Problema di conduzione del calore con sorgente localizzata
diffusion_function = "0.5 + 0.3*cos(2*pi*x)*cos(2*pi*y)"
transport_function_x = "0.0"
transport_function_y = "0.0"
reaction_function = "-0.2*x*y"
forcing_function = "100*exp(-50*((x-0.25)*(x-0.25) + (y-0.75)*(y-0.75))) + 50*exp(-30*((x-0.75)*(x-0.75) + (y-0.25)*(y-0.25)))"

# Temperature prescritte sui bordi (Dirichlet) e flussi sui lati (Neumann)
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "20.0 + 10*sin(pi*y)"

[[boundary_conditions]]
type = "neumann"
tag = 1
function = "5*x*(1-x)"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "30.0 + 5*cos(pi*x)"

[[boundary_conditions]]
type = "neumann"
tag = 3
function = "-2*y*y"
