[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-5_gmsh22.msh"
output_file = "output/poisson_test"

[quadrature]
type = "order2"

[equation]
# Problema di Poisson puro: -laplace(u) = f (no transport, no reaction)
diffusion_coefficient = 1.0
transport_coefficient = 0.0
reaction_coefficient = 0.0
forcing_function = "2.0*(x + y) - 2.0*(x*x + y*y)"

# Condizioni di Dirichlet omogenee su tutti i bordi
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "0.0"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "0.0"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "0.0"

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "0.0"

[solver]
tolerance = 1e-14
max_iterations = 2000
method = "direct"
