[problem]
dimension = 1
1d_size = 100
output_file = "output/solution_1d"

[quadrature]
type = "order2"

[equation]
# Equazione 1D: -d/dx(D * du/dx) + b * du/dx + sigma*u = f
diffusion_function = "1.0"
transport_function_x = "0.0"
reaction_function = "0.0"
forcing_function = "4*pi*pi*sin(2*pi*x)"

# u(0) = 0 (Dirichlet al punto sinistro)
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "0.0"

# du/dn(1) = 1 (Neumann al punto destro)
[[boundary_conditions]]
type = "neumann"
tag = 1
function = "2*pi*sin(2*pi*x)"
