[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.012500_gmsh22.msh"
output_file = "output/solution_2d"

[quadrature]
type = "order2"

[equation]
diffusion_function = "1.0"
transport_function_x = "0.0"
transport_function_y = "0.0"
reaction_function = "0.0"
forcing_function = "0"

# Condizioni di Dirichlet: u = 0 sui bordi 0, 1, 2, 3
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "x+y"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "x+y"

[[boundary_conditions]]
type = "dirichlet" 
tag = 2
function = "x+y"

# Condizione di Neumann: du/dn = 1 sul bordo 3
[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "x+y"
