[problem]
dimension = 2
mesh_file = "mesh/mesh-square-5_gmsh22.msh"
output_file = "output/solution_2d"

[quadrature]
type = "order2"

[equation]
# Coefficienti dell'equazione: -div(D*grad(u)) + b*grad(u) + sigma*u = f
diffusion_coefficient = 1.0
transport_coefficient = 0.1
reaction_coefficient = 0.1
forcing_function = "sin(pi*x)*sin(pi*y)"

# Condizioni di Dirichlet: u = 0 sui bordi 1, 2, 3
[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "0.0"

[[boundary_conditions]]
type = "dirichlet" 
tag = 2
function = "0.0"

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "0.0"

# Condizione di Neumann: du/dn = 1 sul bordo 4
[[boundary_conditions]]
type = "neumann"
tag = 4
function = "1.0"

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"
