# Time-dependent 2D diffusion-reaction problem
# Mixed boundary conditions: Dirichlet and time-dependent Neumann

[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.050000_gmsh22.msh"
output_file = "output/wobble_2d_td"
time_dependent = true

[quadrature]
type = "order2"

[equation]
diffusion_coefficient = 1.0
transport_coefficient_x = 0.0
transport_coefficient_y = 0.0
reaction_coefficient = 1

[time_dependent]
final_time = 1.0
time_step = 0.02
theta = 0.5  # Crank-Nicolson
initial_condition = "0.0"
forcing_function_td = "sin(2.0 * pi * (x + y)) * 2.0 * pi * cos(2.0 * pi*t) - ((-2.0) * pi*2.0 * pi*sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t) + (-2.0) * pi*2.0 * pi*sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)) + sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)"

# Mixed boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
time_function = "sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)"  # time-dependent Dirichlet

[[boundary_conditions]]
type = "dirichlet"
tag = 1
time_function = "sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)"  # time-dependent Dirichlet

[[boundary_conditions]]
type = "dirichlet"
tag = 2
time_function = "sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)"  # time-dependent Dirichlet

[[boundary_conditions]]
type = "dirichlet"
tag = 3
time_function = "sin(2.0 * pi * (x + y)) * sin(2.0 * pi*t)"  # time-dependent Dirichlet

[solver]
tolerance = 1e-12
max_iterations = 1000
method = "direct"
