[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.050000_gmsh22.msh"
output_file = "output/good_examples/exponential_2d"

[quadrature]
type = "order4"

[equation]
# Exact solution: u(x,y) = exp(-x)*cos(pi*y)
# With D=0.5, b=(2, -1), r=3
diffusion_function = "0.5"
transport_function_x = "2.0"
transport_function_y = "-1.0"
reaction_function = "3.0"
forcing_function = "exp(-x)*(cos(pi*y)*(0.5*pi*pi + 0.5) + pi*sin(pi*y))"

[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "exp(-x)*cos(pi*y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "exp(-x)*cos(pi*y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "exp(-x)*cos(pi*y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "exp(-x)*cos(pi*y)"
