[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.050000_gmsh22.msh"
output_file = "output/good_example_gaussian_bump_2d"

[quadrature]
type = "order2"

[equation]
# Exact solution: u(x,y) = exp(-((x-0.5)^2 + (y-0.5)^2)/0.1)  
# PDE coefficients: D=1, b=(0.1,0.1), r=0.1
diffusion_function = "1.0"
transport_function_x = "0.1"
transport_function_y = "0.1"
reaction_function = "0.1"
forcing_function = "exp(-10*((x-0.5)*(x-0.5) + (y-0.5)*(y-0.5)))*(40*((x-0.5)*(x-0.5) + (y-0.5)*(y-0.5)) - 4 + 0.2*(x+y-1) + 0.1)"

# Boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "exp(-10*((x-0.5)*(x-0.5) + (y-0.5)*(y-0.5)))"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "exp(-10*((x-0.5)*(x-0.5) + (y-0.5)*(y-0.5)))"

# Top boundary y=1 
[[boundary_conditions]]
type = "neumann"
tag = 2
function = "0.0"

# Left boundary x=0
[[boundary_conditions]]
type = "neumann"
tag = 3
function = "0.0"
