[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.050000_gmsh22.msh"
output_file = "output/good_example_polynomial_2d"

[quadrature]
type = "order2"

[equation]
# Exact solution: u(x,y) = x^2*y*(1-y)
# With D=1, b=(0.5, 0), r=1
diffusion_function = "1.0"
transport_function_x = "0.5"
transport_function_y = "0.0"
reaction_function = "1.0"
forcing_function = "6*x*x + y*(1-y)*(-2 + x + x*x)"

[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "x*x*y*(1-y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "x*x*y*(1-y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "x*x*y*(1-y)"

[[boundary_conditions]]
type = "neumann"
tag = 3
function = "0.0"
