[problem]
dimension = 1
grid_size = 50
output_file = "output/good_example_polynomial_1d"

[quadrature]
type = "order2"

[equation]
# Exact solution: u(x) = x^3 - x^2 + x
# PDE coefficients: D=2, b=1, r=0.5
diffusion_coefficient = 2.0
transport_function_x = 1.0
reaction_coefficient = 0.5
forcing_function = "0.5*x*x*x + 2.5*x*x - 13.5*x + 5"

# Boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "x*x*x - x*x + x"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "x*x*x - x*x + x"
