[problem]
dimension = 1
1d_size = 1000
output_file = "output/MY_sinusoidal_1d"

[quadrature]
type = "order4"

[equation]
# Exact solution: u(x) = sin(2*pi*x)
diffusion_coefficient = "1.0"
transport_function_x = "0.0"
reaction_function = "1.0"
forcing_function = "40.4784176044 * sin(2*pi*x)"

# Boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "0"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "0"
