[problem]
dimension = 3
mesh_file = "../mesh/mesh-cube-10_gmsh22.msh"
output_file = "output/good_examples/trigonometric_3d"

[quadrature]
type = "order2"

[equation]
diffusion_function = "2.0"
transport_function_x = "1.0"
transport_function_y = "0.5"
transport_function_z = "0.8"
reaction_function = "0.5"
forcing_function = "2*pi^2*(sin(pi*x)*sin(pi*y)*sin(pi*z)) + pi*(cos(pi*x)*sin(pi*y)*sin(pi*z) + 0.5*sin(pi*x)*cos(pi*y)*sin(pi*z) + 0.8*sin(pi*x)*sin(pi*y)*cos(pi*z)) + 0.5*sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 2
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 3
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 4
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"

[[boundary_conditions]]
type = "dirichlet"
tag = 5
function = "sin(pi*x)*sin(pi*y)*sin(pi*z)"
