[problem]
dimension = 2
mesh_file = "../mesh/mesh-square-h0.050000_gmsh22.msh"
output_file = "output/good_example_variable_coeffs_2d"

[quadrature]
type = "order2"

[equation]
# Exact solution: u(x,y) = xy(1-x)(1-y)
# PDE coefficients: D=(1+x+y), b=(x,y), r=xy (variable)
diffusion_function = "1 + x + y"
transport_function_x = "x"
transport_function_y = "y"
reaction_function = "x*y"
forcing_function = "2*(1+x+y)*(1-x-y+2*x*y) + x*x*y*(1-y) + x*y*y*(1-x) + x*x*y*y*(1-x)*(1-y)"

# Boundary conditions
[[boundary_conditions]]
type = "dirichlet"
tag = 0
function = "x*y*(1-x)*(1-y)"

[[boundary_conditions]]
type = "dirichlet"
tag = 1
function = "x*y*(1-x)*(1-y)"

[[boundary_conditions]]
type = "neumann"
tag = 2
function = "0.0"

[[boundary_conditions]]
type = "neumann"
tag = 3
function = "0.0"
